#!/bin/bash

# 这个脚本帮助将NativeCOS文件添加到Xcode项目中
echo "=== 将NativeCOS添加到Xcode项目的步骤 ==="
echo ""
echo "1. 打开Xcode项目："
echo "   cd ios && open MyCrossPlatformApp.xcworkspace"
echo ""
echo "2. 在项目导航器中："
echo "   - 展开 MyCrossPlatformApp 项目"
echo "   - 展开 MyCrossPlatformApp 文件夹（不是项目根目录）"
echo "   - 右键点击 MyCrossPlatformApp 文件夹"
echo "   - 选择 'Add Files to MyCrossPlatformApp'"
echo ""
echo "3. 选择文件："
echo "   - 导航到 ios/MyCrossPlatformApp/ 目录"
echo "   - 选择 NativeCOS.h 和 NativeCOS.m"
echo "   - 确保 'Add to target' 中选中了 MyCrossPlatformApp"
echo "   - 点击 'Add'"
echo ""
echo "4. 检查Build Phases："
echo "   - 选择项目根目录 MyCrossPlatformApp"
echo "   - 选择 'Build Phases' 标签"
echo "   - 展开 'Compile Sources'"
echo "   - 确认 NativeCOS.m 在列表中"
echo ""
echo "5. 检查Header Search Paths："
echo "   - 选择项目根目录 MyCrossPlatformApp"
echo "   - 选择 'Build Settings' 标签"
echo "   - 搜索 'Header Search Paths'"
echo "   - 确保包含了 \$(SRCROOT)/../node_modules/react-native/React 路径"
echo ""
echo "6. 重新构建项目："
echo "   cd .. && npx react-native run-ios"
echo ""
echo "注意：如果文件已经存在，Xcode会提示是否替换，选择替换即可。"
